// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// selectControls
DataFrame selectControls(const List& nestingCohorts, const List& cases, const List& visits, const bool firstOutcomeOnly, const int washoutPeriod, const int controlsPerCase, const bool matchOnAge, const double ageCaliper, const bool matchOnGender, const bool matchOnProvider, const bool matchOnVisitDate, const int visitDateCaliper, const bool matchOnTimeInCohort, const int daysInCohortCaliper);
RcppExport SEXP CaseControl_selectControls(SEXP nestingCohortsSEXP, SEXP casesSEXP, SEXP visitsSEXP, SEXP firstOutcomeOnlySEXP, SEXP washoutPeriodSEXP, SEXP controlsPerCaseSEXP, SEXP matchOnAgeSEXP, SEXP ageCaliperSEXP, SEXP matchOnGenderSEXP, SEXP matchOnProviderSEXP, SEXP matchOnVisitDateSEXP, SEXP visitDateCaliperSEXP, SEXP matchOnTimeInCohortSEXP, SEXP daysInCohortCaliperSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const List& >::type nestingCohorts(nestingCohortsSEXP);
    Rcpp::traits::input_parameter< const List& >::type cases(casesSEXP);
    Rcpp::traits::input_parameter< const List& >::type visits(visitsSEXP);
    Rcpp::traits::input_parameter< const bool >::type firstOutcomeOnly(firstOutcomeOnlySEXP);
    Rcpp::traits::input_parameter< const int >::type washoutPeriod(washoutPeriodSEXP);
    Rcpp::traits::input_parameter< const int >::type controlsPerCase(controlsPerCaseSEXP);
    Rcpp::traits::input_parameter< const bool >::type matchOnAge(matchOnAgeSEXP);
    Rcpp::traits::input_parameter< const double >::type ageCaliper(ageCaliperSEXP);
    Rcpp::traits::input_parameter< const bool >::type matchOnGender(matchOnGenderSEXP);
    Rcpp::traits::input_parameter< const bool >::type matchOnProvider(matchOnProviderSEXP);
    Rcpp::traits::input_parameter< const bool >::type matchOnVisitDate(matchOnVisitDateSEXP);
    Rcpp::traits::input_parameter< const int >::type visitDateCaliper(visitDateCaliperSEXP);
    Rcpp::traits::input_parameter< const bool >::type matchOnTimeInCohort(matchOnTimeInCohortSEXP);
    Rcpp::traits::input_parameter< const int >::type daysInCohortCaliper(daysInCohortCaliperSEXP);
    __result = Rcpp::wrap(selectControls(nestingCohorts, cases, visits, firstOutcomeOnly, washoutPeriod, controlsPerCase, matchOnAge, ageCaliper, matchOnGender, matchOnProvider, matchOnVisitDate, visitDateCaliper, matchOnTimeInCohort, daysInCohortCaliper));
    return __result;
END_RCPP
}
