# This file has been autogenerated. Do not change by hand. 

#' Create a parameter object for the function getDbCaseData
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param useNestingCohort                    Should the study be nested in a cohort (e.g. people witha
#'                                            specific indication)? If not, the study will be nestedin
#'                                            the general population.
#' @param useObservationEndAsNestingEndDate   When using a nesting cohort, should the observationperiod
#'                                            end date be used instead of the cohort end date?
#' @param getVisits                           Get data on visits? This is needed when matching on
#'                                            visitdate is requested later on.
#' @param studyStartDate                      A calendar date specifying the minimum date where data
#'                                            isused. Date format is 'yyyymmdd'.
#' @param studyEndDate                        A calendar date specifying the maximum date where data
#'                                            isused. Date format is 'yyyymmdd'.
#' @param maxNestingCohortSize                If the nesting cohort is larger thanthis number it will
#'                                            be sampled to this size. maxCohortSize = 0indicates no
#'                                            maximum size.
#' @param maxCasesPerOutcome                  If there are more than this number of cases for a
#'                                            singleoutcome cases will be sampled to this size.
#'                                            maxCasesPerOutcome = 0indicates no maximum size.
#'
#' @export
createGetDbCaseDataArgs <- function(useNestingCohort = FALSE,
                                    useObservationEndAsNestingEndDate = TRUE,
                                    getVisits = TRUE,
                                    studyStartDate = "",
                                    studyEndDate = "",
                                    maxNestingCohortSize = 1e+07,
                                    maxCasesPerOutcome = 5e+05) {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createGetDbCaseDataArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}

#' Create a parameter object for the function selectControls
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param firstOutcomeOnly           Use the first outcome per person?
#' @param washoutPeriod              Minimum required numbers of days of observation for inclusion
#'                                   aseither case or control.
#' @param controlSelectionCriteria   Either a matchingCriteria object as generated using the
#'                                   createMatchingCriteria function, or a samplingCriteriaobject as
#'                                   generated using the link{createSamplingCriteria}function.
#' @param minAge                     Minimum age at which patient time will be included in the
#'                                   analysis.Note that information prior to the min age is still used
#'                                   to determineexposure status after the minimum age (e.g. when a
#'                                   prescription wasstarted just prior to reaching the minimum age).
#'                                   Also, outcomesoccurring before the minimum age is reached will be
#'                                   considered asprior outcomes when using first outcomes only. Age
#'                                   should be specifiedin years, but non-integer values are allowed.
#'                                   If not specified, no agerestriction will be applied.
#' @param maxAge                     Maximum age at which patient time will be included in the
#'                                   analysis. Ageshould be specified in years, but non-integer values
#'                                   are allowed. If notspecified, no age restriction will be applied.
#'
#' @export
createSelectControlsArgs <- function(firstOutcomeOnly = TRUE,
                                     washoutPeriod = 180,
                                     controlSelectionCriteria = createMatchingCriteria(),
                                     minAge = NULL,
                                     maxAge = NULL) {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createSelectControlsArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}

#' Create a parameter object for the function getDbExposureData
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param covariateSettings   An object of type covariateSettings as created using
#'                            thecreateCovariateSettings function in theFeatureExtraction package. If
#'                            NULL then no covariate data isretrieved.
#'
#' @export
createGetDbExposureDataArgs <- function(covariateSettings = NULL) {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createGetDbExposureDataArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}

#' Create a parameter object for the function createCaseControlData
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param firstExposureOnly       Should only the first exposure per subject be included?
#' @param riskWindowStart         The start of the risk window (in days) relative to the index
#'                                date.This number should be non-positive.
#' @param riskWindowEnd           The end of the risk window (in days) relative to the index date.
#'                                Thisnumber should be non-positive.
#' @param exposureWashoutPeriod   Minimum required numbers of days of observation for inclusion of an
#'                                exposure.
#'
#' @export
createCreateCaseControlDataArgs <- function(firstExposureOnly = FALSE,
                                            riskWindowStart = 0,
                                            riskWindowEnd = 0,
                                            exposureWashoutPeriod = 0) {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createCreateCaseControlDataArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}

#' Create a parameter object for the function fitCaseControlModel
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param useCovariates         Whether to use the covariates in the caseControlsExposure.
#' @param excludeCovariateIds   Exclude these covariates from the model.
#' @param includeCovariateIds   Include only these covariates in the model.
#' @param prior                 The prior used to fit the model. SeecreatePrior for details.
#' @param control               The control object used to control the cross-validation used
#'                              todetermine the hyperparameters of the prior (if applicable).
#'                              SeecreateControl for details.
#'
#' @export
createFitCaseControlModelArgs <- function(useCovariates = FALSE,
                                          excludeCovariateIds = c(),
                                          includeCovariateIds = c(),
                                          prior = createPrior("laplace", useCrossValidation = TRUE),
                                          control = createControl(cvType = "auto",
                                                                  startingVariance = 0.01,
                                                                  tolerance = 2e-07,
                                                                  cvRepetitions = 10,
                                                                  selectorType = "byPid",
                                                                  noiseLevel = "quiet")) {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createFitCaseControlModelArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}
