# This file has been autogenerated. Do not change by hand. 

#' Create a parameter object for the function getDbCaseData
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param useNestingCohort                    Should the study be nested in a cohort (e.g. people witha
#'                                            specific indication)? If not, the study will be nested
#'                                            inthe general population.
#' @param useObservationEndAsNestingEndDate   When using a nesting cohort, should the observation
#'                                            period enddate be used instead of the cohort end date?
#' @param getVisits                           Get data on visits? This is needed when matching on visit
#'                                            date isrequested later on.
#' @param studyStartDate                      A calendar date specifying the minimum date where data
#'                                            isused. Date format is 'yyyymmdd'.
#' @param studyEndDate                        A calendar date specifying the maximum date where data
#'                                            isused. Date format is 'yyyymmdd'.
#'
#' @export
createGetDbCaseDataArgs <- function(useNestingCohort = FALSE,
                                    useObservationEndAsNestingEndDate = TRUE,
                                    getVisits = TRUE,
                                    studyStartDate = "",
                                    studyEndDate = "") {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createGetDbCaseDataArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}

#' Create a parameter object for the function selectControls
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param outcomeId               The outcome ID of the cases for which we need to pick controls.
#' @param firstOutcomeOnly        Use the first outcome per person?
#' @param washoutPeriod           Minimum required numbers of days of observation for inclusion as
#'                                either case or control.
#' @param controlsPerCase         Maximum number of controls to select per case.
#' @param matchOnAge              Match on age?
#' @param ageCaliper              Maximum difference (in years) in age when matching on age.
#' @param matchOnGender           Match on gender?
#' @param matchOnProvider         Match on provider (as specified in the person table)?
#' @param matchOnVisitDate        Should the index date of the control be changed to the nearest visit
#'                                date?
#' @param visitDateCaliper        Maximum difference (in days) between the index date and the visit
#'                                date when matching on visit date.
#' @param removedUnmatchedCases   Should cases with no matched controls be removed?
#'
#' @export
createSelectControlsArgs <- function(outcomeId,
                                     firstOutcomeOnly = TRUE,
                                     washoutPeriod = 180,
                                     controlsPerCase = 2,
                                     matchOnAge = TRUE,
                                     ageCaliper = 2,
                                     matchOnGender = TRUE,
                                     matchOnProvider = FALSE,
                                     matchOnVisitDate = FALSE,
                                     visitDateCaliper = 30,
                                     removedUnmatchedCases = TRUE) {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createSelectControlsArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}

#' Create a parameter object for the function createCaseControlData
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param firstExposureOnly   Should only the first exposure per subject be included?
#' @param riskWindowStart     The start of the risk window (in days) relative to the index date. This
#'                            number should be non-positive.
#' @param riskWindowEnd       The end of the risk window (in days) relative to the index date. This
#'                            number should be non-positive.
#'
#' @export
createCreateCaseControlDataArgs <- function(firstExposureOnly = FALSE,
                                            riskWindowStart = 0,
                                            riskWindowEnd = 0) {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createCreateCaseControlDataArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}
