# @file GetExposureData.R
#
# Copyright 2021 Observational Health Data Sciences and Informatics
#
# This file is part of CaseControl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Get exposure data for cases and controls from a database
#'
#' @description
#' If additional exposure data or covariate data is required, this function will send the information
#' on the cases and controls back to the server.
#'
#' Note: For PDW and RedShift, where uploading data can be excrutiatingly slow, you can use bulk loading
#' by preparing the environment as described in the \code{\link[DatabaseConnector]{insertTable}} function
#' in the DatabaseConnection package, and setting \code{tempEmulationSchema} to a schema where you have write
#' privileges (bulk import can only upload to permanent tables).
#'
#' @param connectionDetails        An R object of type\cr\code{connectionDetails} created using the
#'                                 function \code{createConnectionDetails} in the
#'                                 \code{DatabaseConnector} package.
#' @param tempEmulationSchema Some database platforms like Oracle and Impala do not truly support temp tables. To
#'                            emulate temp tables, provide a schema with write privileges where temp tables
#'                            can be created.
#' @param caseControls             A data frame as generated by the \code{\link{selectControls}}
#'                                 function.
#' @param exposureDatabaseSchema   The name of the database schema that is the location where the
#'                                 exposure data used to define the exposure cohorts is available. If
#'                                 exposureTable = DRUG_ERA, exposureDatabaseSchema is not used but
#'                                 assumed to be cdmSchema.  Requires read permissions to this
#'                                 database.
#' @param exposureTable            The tablename that contains the exposure cohorts.  If exposureTable
#'                                 <> drug_era, then expectation is exposureTable has format of COHORT
#'                                 table: cohort_definition_id, subject_id, cohort_start_date,
#'                                 cohort_end_date.
#' @param exposureIds              A list of identifiers to define the exposures of interest. If
#'                                 exposureTable = drug_era, exposureIds should be concept_id. If
#'                                 exposureTable <> drug_era, exposureIds is used to select the
#'                                 cohort_definition_id in the cohort-like table. If no exposureIds are
#'                                 provided, all drugs or cohorts in the exposureTable are included as
#'                                 exposures.
#' @param cdmDatabaseSchema        Needed when constructing covariates using FeatureExtraction: the name of the database schema
#'                                 that contains the OMOP CDM instance.  Requires read permissions to
#'                                 this database. On SQL Server, this should specify both the database
#'                                 and the schema, so for example 'cdm_instance.dbo'.
#' @param covariateSettings        Either an object of type \code{covariateSettings} as created using the
#'                                 \code{createCovariateSettings} function in the
#'                                 \code{FeatureExtraction} package, or an object of type \code{SimpleCovariateSettings}
#'                                 as created using the \code{\link{createSimpleCovariateSettings}} function.
#'                                 If NULL then no covariate data is retrieved.
#' @param caseData                An object of type \code{caseData} as generated using the
#'                                \code{\link{getDbCaseData}} function. If caseData is provided and contains
#'                                the exposure data (see getExposures in the  \code{\link{getDbCaseData}} function,
#'                                and if no covariates need to constructed (covariateSettings = NULL) or only simple
#'                                covariates need to be constructed, then the no connection to the database is used
#'                                to create the exposure data. This may be much more efficient in some situations.
#'
#' @export
getDbExposureData <- function(caseControls,
                              connectionDetails,
                              tempEmulationSchema = getOption("sqlRenderTempEmulationSchema"),
                              exposureDatabaseSchema = NULL,
                              exposureTable = "drug_era",
                              exposureIds = c(),
                              cdmDatabaseSchema = exposureDatabaseSchema,
                              covariateSettings = NULL,
                              caseData = NULL) {
  exposure <- tibble(rowId = c(),
                     exposureId = c(),
                     daysPriorObservation = c(),
                     daysSinceExposureStart = c(),
                     daysSinceExposureEnd = c())
  if (nrow(caseControls) == 0) {
    result <- list(caseControls = caseControls,
                   exposure = data.frame(),
                   metaData = attr(caseControls, "metaData"))
    attr(result$caseControls, "metaData") <- NULL
    result$metaData$hasCovariates <- FALSE
  } else if ((is.null(covariateSettings) || class(covariateSettings) == "SimpleCovariateSettings") &&
             !is.null(caseData) && attr(caseData, "metaData")$hasExposures) {
    ParallelLogger::logInfo("Using pre-fetched exposures in caseData object")

    caseData$caseControls <- caseControls %>%
      mutate(rowId = row_number())
    on.exit(caseData$caseControls <- NULL)

    caseData$caseControlsPlus <- caseData$caseControls %>%
      inner_join(select(caseData$nestingCohorts,
                        .data$personSeqId,
                        .data$observationPeriodStartDate ,
                        .data$endDate,
                        .data$dateOfBirth,
                        .data$genderConceptId),
                 by = "personSeqId") %>%
      filter(.data$indexDate >= .data$observationPeriodStartDate &
               .data$indexDate <= .data$endDate)
    on.exit(caseData$caseControlsPlus <- NULL, add = TRUE)

    exposure <- caseData$exposures %>%
      filter(.data$exposureId %in% exposureIds) %>%
      inner_join(caseData$caseControlsPlus, by = "personSeqId") %>%
      filter(.data$exposureStartDate >= .data$observationPeriodStartDate &
               .data$exposureStartDate <= .data$endDate) %>%
      mutate(daysPriorObservation = .data$exposureStartDate - .data$observationPeriodStartDate,
             daysSinceExposureStart = .data$indexDate - .data$exposureStartDate,
             daysSinceExposureEnd = .data$indexDate - .data$exposureEndDate) %>%
      filter(.data$daysSinceExposureStart >= 0) %>%
      select(.data$rowId, .data$exposureId, .data$daysPriorObservation, .data$daysSinceExposureStart, .data$daysSinceExposureEnd) %>%
      collect()

    caseControls <- caseData$caseControls %>%
      collect()
    result <- list(caseControls = caseControls,
                   exposure = exposure,
                   metaData = attr(caseControls, "metaData"))
    attr(result$caseControls, "metaData") <- NULL

    if (!is.null(covariateSettings) && class(covariateSettings) == "SimpleCovariateSettings") {
      covariateData <- Andromeda::andromeda()

      if (covariateSettings$useDemographicsAgeGroup) {
        covariates <- caseData$caseControlsPlus %>%
          transmute(rowId = .data$rowId,
                    covariateId = 1 + 1000 * floor((.data$indexDate - .data$dateOfBirth) / (365.25*5)),
                    covariateValue = 1) %>% collect()

        covariateRef <- tibble(covariateId = 1 + 1000 * 1:25,
                               covariateName = sprintf("Age %d - %d", 5 * 0:24, 5 * 1:25),
                               analysisId = 1)
        analysisRef <- tibble(analysisId = 1,
                              analysisName = "Age in 5 year groups")

        covariateData$covariates <- covariates
        covariateData$covariateRef <- covariateRef
        covariateData$analysisRef <- analysisRef
      }
      if (covariateSettings$useDemographicsGender) {
        covariates <- caseData$caseControlsPlus %>%
          filter(.data$genderConceptId == 8532) %>%
          transmute(rowId = .data$rowId,
                    covariateId = 1002,
                    covariateValue = 1)
        covariateRef <- tibble(covariateId = 1002,
                               covariateName = "Gender = FEMALE",
                               analysisId = 2)
        analysisRef <- tibble(analysisId = 2,
                              analysisName = "Gender")
        if (covariateSettings$useDemographicsAgeGroup) {
          Andromeda::appendToTable(covariateData$covariates, covariates)
          Andromeda::appendToTable(covariateData$covariateRef, covariateRef)
          Andromeda::appendToTable(covariateData$analysisRef, analysisRef)
        } else {
          covariateData$covariates <- covariates
          covariateData$covariateRef <- covariateRef
          covariateData$analysisRef <- analysisRef
        }
        attr(covariateData, "metaData") <- list(populationSize = nrow(caseControls))
        class(covariateData) <- "CovariateData"
        attr(class(covariateData), "package") <- "FeatureExtraction"
      }
      result$covariateData <- covariateData
      result$metaData$hasCovariates <- TRUE
    } else {
      result$metaData$hasCovariates <- FALSE
    }
  } else {
    connection <- DatabaseConnector::connect(connectionDetails)
    on.exit(DatabaseConnector::disconnect(connection))
    ParallelLogger::logInfo("Uploading cases and controls to database temp table")
    start <- Sys.time()
    caseControls$rowId <- 1:nrow(caseControls)
    data <- caseControls %>%
      transmute(rowId = .data$rowId,
                cohortDefinitionId = 1,
                subjectId = bit64::as.integer64(.data$personId),
                cohortStartDate = Andromeda::restoreDate(.data$indexDate))
    if (connection@dbms %in% c("pdw", "redshift") && !is.null(tempEmulationSchema)) {
      ParallelLogger::logInfo("Attempting to use bulk load for MPP platform.")
      tableName <- paste(tempEmulationSchema, paste(sample(letters, 20), collapse = ""), sep = ".")
      DatabaseConnector::insertTable(connection = connection,
                                     tableName = tableName,
                                     data = as.data.frame(data),
                                     dropTableIfExists = TRUE,
                                     createTable = TRUE,
                                     tempTable = FALSE,
                                     bulkLoad = TRUE,
                                     camelCaseToSnakeCase = TRUE)
      sql <- "
      IF OBJECT_ID('tempdb..#case_controls', 'U') IS NOT NULL
        DROP TABLE #case_controls;

      SELECT * INTO #case_controls FROM @table_name;

      TRUNCATE TABLE @table_name;

      DROP TABLE @table_name;"
      DatabaseConnector::renderTranslateExecuteSql(connection, sql, table_name = tableName, progressBar = FALSE, reportOverallTime = FALSE)
    } else {
      DatabaseConnector::insertTable(connection = connection,
                                     tableName = "#case_controls",
                                     data = data,
                                     dropTableIfExists = TRUE,
                                     createTable = TRUE,
                                     tempTable = TRUE,
                                     tempEmulationSchema = tempEmulationSchema,
                                     camelCaseToSnakeCase = TRUE)
    }
    delta <- Sys.time() - start
    ParallelLogger::logInfo(paste("Uploading took", signif(delta, 3), attr(delta, "units")))

    ParallelLogger::logInfo("Loading exposure data from server")
    start <- Sys.time()
    renderedSql <- SqlRender::loadRenderTranslateSql("queryExposure.sql",
                                                     packageName = "CaseControl",
                                                     dbms = connectionDetails$dbms,
                                                     tempEmulationSchema = tempEmulationSchema,
                                                     cdm_database_schema = cdmDatabaseSchema,
                                                     exposure_database_schema = exposureDatabaseSchema,
                                                     exposure_table = exposureTable,
                                                     exposure_ids = exposureIds)
    exposure <- DatabaseConnector::querySql(connection, renderedSql, snakeCaseToCamelCase = TRUE)
    delta <- Sys.time() - start
    ParallelLogger::logInfo(paste("Loading took", signif(delta, 3), attr(delta, "units")))

    if (!is.null(covariateSettings)) {
      covariateData <- FeatureExtraction::getDbCovariateData(connection = connection,
                                                             oracleTempSchema = tempEmulationSchema,
                                                             cdmDatabaseSchema = cdmDatabaseSchema,
                                                             cdmVersion = 5,
                                                             cohortTable = "#case_controls",
                                                             cohortTableIsTemp = TRUE,
                                                             rowIdField = "row_id",
                                                             covariateSettings = covariateSettings)
    }
    sql <- "TRUNCATE TABLE #case_controls; DROP TABLE #case_controls;"
    sql <- SqlRender::translate(sql = sql,
                                targetDialect = connectionDetails$dbms,
                                tempEmulationSchema = tempEmulationSchema)
    DatabaseConnector::executeSql(connection, sql, progressBar = FALSE, reportOverallTime = FALSE)

    result <- list(caseControls = caseControls, exposure = exposure, metaData = attr(caseControls,
                                                                                     "metaData"))
    attr(result$caseControls, "metaData") <- NULL
    if (!is.null(covariateSettings)) {
      result$covariateData <- covariateData
      result$metaData$hasCovariates <- TRUE
      result$metaData$covariateMetaData <- attr(covariateData, "metaData")
    } else {
      result$metaData$hasCovariates <- FALSE
    }
  }
  result$caseControls$personSeqId <- NULL
  result$caseControls$personId <- NULL
  result$caseControls$indexDate <- NULL
  class(result) <- "caseControlsExposure"
  return(result)
}

#' Save the caseControlsExposure data to folder
#'
#' @description
#' \code{saveCaseControlsExposure} saves an object of type caseControlsExposure to folder.
#'
#' @param caseControlsExposure   An object of type \code{caseControlsExposure} as generated using
#'                               \code{\link{getDbExposureData}}.
#' @param folder                 The name of the folder where the data will be written. The folder
#'                               should not yet exist.
#'
#' @details
#' The data will be written to a set of files in the specified folder.
#'
#' @export
saveCaseControlsExposure <- function(caseControlsExposure, folder) {
  if (missing(caseControlsExposure))
    stop("Must specify caseControlsExposure")
  if (missing(folder))
    stop("Must specify folder")
  if (class(caseControlsExposure) != "caseControlsExposure")
    stop("Data not of class caseControlsExposure")

  dir.create(folder)
  saveRDS(caseControlsExposure$caseControls, file = file.path(folder, "caseControls.rds"))
  saveRDS(caseControlsExposure$exposure, file = file.path(folder, "exposure.rds"))
  saveRDS(caseControlsExposure$metaData, file = file.path(folder, "metaData.rds"))
  if (caseControlsExposure$metaData$hasCovariates) {
    FeatureExtraction::saveCovariateData(caseControlsExposure$covariateData, file.path(folder, "covariateData.zip"))
  }
  invisible(TRUE)
}

#' Load the caseControlsExposure data from a folder
#'
#' @description
#' \code{loadCaseControlsExposure} loads an object of type caseControlsExposure from a folder in the
#' file system.
#'
#' @param folder     The name of the folder containing the data.
#' @param readOnly   If true, the data is opened read only.
#'
#' @details
#' The data will be written to a set of files in the folder specified by the user.
#'
#' @return
#' An object of class \code{caseControlsExposure}.
#'
#' @export
loadCaseControlsExposure <- function(folder, readOnly = TRUE) {
  if (!file.exists(folder))
    stop(paste("Cannot find folder", folder))
  if (!file.info(folder)$isdir)
    stop(paste("Not a folder:", folder))

  caseControls <- readRDS(file.path(folder, "caseControls.rds"))
  exposure <- readRDS(file.path(folder, "exposure.rds"))
  metaData <- readRDS(file.path(folder, "metaData.rds"))
  result <- list(caseControls = caseControls, exposure = exposure, metaData = metaData)
  if (result$metaData$hasCovariates) {
    result$covariateData <- FeatureExtraction::loadCovariateData(file.path(folder, "covariateData.zip"))
  }
  class(result) <- "caseControlsExposure"
  return(result)
}

#' Create simple covariate settings
#'
#' @details
#' Create simple settings for covariates that can be constructed using only the
#' data in the \code{CaseData} object.
#'
#' @param useDemographicsAgeGroup  Age of the subject on the index date (in 5 year age groups).
#' @param useDemographicsGender    Gender of the subject.
#'
#' @return
#' An object of type \code{SimpleCovariateSettings}
#'
#' @export
createSimpleCovariateSettings <- function(useDemographicsAgeGroup = TRUE,
                                          useDemographicsGender = TRUE) {
  settings <- list(useDemographicsAgeGroup = useDemographicsAgeGroup,
                   useDemographicsGender = useDemographicsGender)
  class(settings) <- "SimpleCovariateSettings"
  return(settings)
}
