# @file GetExposureData.R
#
# Copyright 2016 Observational Health Data Sciences and Informatics
#
# This file is part of CaseControl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#' Get exposure data for cases and controls from a database
#'
#' @param connectionDetails            An R object of type\cr\code{connectionDetails} created using the
#'                                     function \code{createConnectionDetails} in the
#'                                     \code{DatabaseConnector} package.
#' @param oracleTempSchema                A schema where temp tables can be created in Oracle.
#' @param caseControls                 A data frame as generated by the \code{\link{selectControls}} function.
#' @param exposureDatabaseSchema          The name of the database schema that is the location where
#'                                        the exposure data used to define the exposure cohorts is
#'                                        available. If exposureTable = DRUG_ERA,
#'                                        exposureDatabaseSchema is not used but assumed to be
#'                                        cdmSchema.  Requires read permissions to this database.
#' @param exposureTable                   The tablename that contains the exposure cohorts.  If
#'                                        exposureTable <> drug_era, then expectation is exposureTable
#'                                        has format of COHORT table: cohort_definition_id, subject_id,
#'                                        cohort_start_date, cohort_end_date.
#' @param exposureIds                     A list of identifiers to define the exposures of interest. If
#'                                        exposureTable = drug_era, exposureIds should be concept_id.
#'                                        If exposureTable <> drug_era, exposureIds is used to select
#'                                        the cohort_definition_id in the cohort-like table. If no
#'                                        exposureIds are provided, all drugs or cohorts in the
#'                                        exposureTable are included as exposures.
#'
#' @export
getDbExposureData <- function(connectionDetails,
                            caseControls,
                            oracleTempSchema = NULL,
                            exposureDatabaseSchema,
                            exposureTable = "drug_era",
                            exposureIds = c()) {
  connection <- DatabaseConnector::connect(connectionDetails)
  writeLines("Uploading cases and controls to database temp table")
  start <- Sys.time()
  data <- caseControls[, c("personId", "indexDate")]
  colnames(data) <- SqlRender::camelCaseToSnakeCase(colnames(data))
  DatabaseConnector::insertTable(connection = connection,
                                 tableName = "#case_controls",
                                 data = data,
                                 dropTableIfExists = TRUE,
                                 createTable = TRUE,
                                 tempTable = TRUE,
                                 oracleTempSchema = oracleTempSchema)
  delta <- Sys.time() - start
  writeLines(paste("Uploading took", signif(delta, 3), attr(delta, "units")))

  writeLines("Loading exposure data from server")
  start <- Sys.time()
  renderedSql <- SqlRender::loadRenderTranslateSql("queryExposure.sql",
                                                   packageName = "CaseControl",
                                                   dbms = connectionDetails$dbms,
                                                   oracleTempSchema = oracleTempSchema,
                                                   exposure_database_schema = exposureDatabaseSchema,
                                                   exposure_table = exposureTable,
                                                   exposure_ids = exposureIds)
  exposure <- DatabaseConnector::querySql(connection, renderedSql)
  colnames(exposure) <- SqlRender::snakeCaseToCamelCase(colnames(exposure))
  delta <- Sys.time() - start
  writeLines(paste("Loading took", signif(delta, 3), attr(delta, "units")))

  sql <- "TRUNCATE TABLE #case_controls; DROP TABLE #case_controls;"
  sql <- SqlRender::translateSql(sql, targetDialect = connectionDetails$dbms, oracleTempSchema = oracleTempSchema)$sql
  DatabaseConnector::executeSql(connection, sql, progressBar = FALSE, reportOverallTime = FALSE)
  RJDBC::dbDisconnect(connection)

  result <- list(caseControls = caseControls, exposure = exposure)
  class(result) <- "caseControlsExposure"
  return(result)
}
