# @file PackageMaintenance
#
# Copyright 2018 Observational Health Data Sciences and Informatics
#
# This file is part of CaseControl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Format and check code
OhdsiRTools::formatRFolder()
OhdsiRTools::checkUsagePackage("CaseControl")
OhdsiRTools::updateCopyrightYearFolder()

# Create manual and vignette
if (.Platform$OS.type == "unix") {
  system("rm extras/CaseControl.pdf")
  system("R CMD Rd2pdf ./ --output=extras/CaseControl.pdf")
} else {
  shell("rm extras/CaseControl.pdf")
  shell("R CMD Rd2pdf ./ --output=extras/CaseControl.pdf")
}

rmarkdown::render("vignettes/SingleStudies.Rmd",
                  output_file = "../inst/doc/SingleStudies.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          number_sections = TRUE))

rmarkdown::render("vignettes/MultipleAnalyses.Rmd",
                  output_file = "../inst/doc/MultipleAnalyses.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          number_sections = TRUE))

pkgdown::build_site()

# Create arg functions:
library(CaseControl)
rCode <- c("# This file has been autogenerated. Do not change by hand. ")
rCode <- ParallelLogger::createArgFunction("getDbCaseData",
                                        excludeArgs = c("connectionDetails",
                                                        "cdmDatabaseSchema",
                                                        "oracleTempSchema",
                                                        "outcomeDatabaseSchema",
                                                        "outcomeTable",
                                                        "outcomeIds",
                                                        "nestingCohortDatabaseSchema",
                                                        "nestingCohortTable",
                                                        "nestingCohortId",
                                                        "getExposures",
                                                        "exposureDatabaseSchema",
                                                        "exposureTable",
                                                        "exposureIds"),
                                        rCode = rCode)
rCode <- ParallelLogger::createArgFunction("selectControls",
                                        excludeArgs = c("caseData", "outcomeId"),
                                        rCode = rCode)
rCode <- ParallelLogger::createArgFunction("getDbExposureData",
                                        excludeArgs = c("caseControls",
                                                        "connectionDetails",
                                                        "oracleTempSchema",
                                                        "exposureDatabaseSchema",
                                                        "exposureTable",
                                                        "exposureIds",
                                                        "cdmDatabaseSchema",
                                                        "caseData"),
                                        rCode = rCode)
rCode <- ParallelLogger::createArgFunction("createCaseControlData",
                                        excludeArgs = c("caseControlsExposure", "exposureId"),
                                        rCode = rCode)
rCode <- ParallelLogger::createArgFunction("fitCaseControlModel",
                                        excludeArgs = c("caseControlData", "caseControlsExposure"),
                                        rCode = rCode)
writeLines(rCode, "r/CreateArgFunctions.R")
OhdsiRTools::formatRFile("r/CreateArgFunctions.R")
